### ISSUE TITLE
Required Files Already Provided

### ISSUE THREAD

**Issue by AwlsomeAlex** [AwlsomeAlex/ReactOS-Downloader#12]
In the Windows Branch, could you add the files that you used to test your script to easily provide the files needed for the script?

**Comment by Bassa31** [comment]
Ok sorry but I will upload this file

**Comment by AwlsomeAlex** [comment]
Thanks @Bassa31

**Comment by AwlsomeAlex** [comment]
![capture](https://cloud.githubusercontent.com/assets/11639639/14942448/73745202-0f8b-11e6-9e58-de7428ea3109.PNG)
Mind providing the files so the User doesn't have to install themselves? @Bassa31

**Comment by Bassa31** [comment]
Okay! I didn t know Wget for Windows 
You must download my file zip (because there is curl And 7z)

**Comment by Bassa31** [comment]
I will upload 7z file And wget :)
