### ISSUE TITLE
Catch up to current RC

### ISSUE THREAD

**Issue by AwlsomeAlex** [AwlsomeAlex/ReactOS-Downloader#15]
Could you update your Windows Batch File to match the Linux Script?
Some New Additions are:
* Stable Download Support + Extraction (.zip)
* RC Download Support (Already Extracted File to be Downloaded)

Thanks. I'll move the deadline back if it isn't enough time, and when it's ready, please request a pull. :)

**Comment by Bassa31** [comment]
Oh yeah! Maybe next update will be big :)

**Comment by AwlsomeAlex** [comment]
Alrighty! 👍  I'll release a RC for the Windows Edition this afternoon, i'm just making minor changes (Including Namechange and Script Name Change.) [Its Awl(not i)someAlex btw. :)] Is it okay that I change the name to ReactOS-Downloader-Windows.bash?

**Comment by Bassa31** [comment]
.bash is for linux 
.bat is for Windows 
I can upload a exe if you want

**Comment by Bassa31** [comment]
Close as fixed

**Comment by AwlsomeAlex** [comment]
I meant bat. Ive been using Linux too much. XD @Bassa31
