### ISSUE TITLE
ReactOS Downloader Malware?

### ISSUE THREAD

**Issue by AwlsomeAlex** [AwlsomeAlex/ReactOS-Downloader#18]
Okay, so we got a problem. The ReactOS Downloader.exe is being identified as Malware by Windows Defender, with it being automatically deleted. Any reason why this is happening @Bassa31 ?

**Comment by Bassa31** [comment]
Maybe this appens because it's a exe and its name has downloader ------> virus.... I will check this

**Comment by AwlsomeAlex** [comment]
Thank you. @Bassa31 4.0 won't be released until this is fixed, so I'll keep working on the Linux Downloader.

**Comment by Bassa31** [comment]
![screenshot_2016-05-07-17-27-51](https://cloud.githubusercontent.com/assets/17526237/15092956/54c3636e-1479-11e6-9a99-e9ba2fa71c86.png)
/0\ We need to edit file ---> exe to Bat. I will fix this

**Comment by Bassa31** [comment]
Close as fixed for now :)

**Comment by AwlsomeAlex** [comment]
Problem still remains with the name Downloader.exe Why is this happening?

**Comment by Bassa31** [comment]
I don t know why but downloader is a bad name for antivirus

**Comment by Bassa31** [comment]
I understand this:
If we have got exe from batch ---> virus!
So for now only batch
