### ISSUE TITLE
Windows Downloader Automatically Fails

### ISSUE THREAD

**Issue by AwlsomeAlex** [AwlsomeAlex/ReactOS-Downloader#20]
When I try to use the downloader, I get to the point of Livecd or Bootcd, then it starts download with curl, then automatically fails, along with it extracting nothing. However, it seems as both are downloaded.

**Comment by AwlsomeAlex** [comment]
I found the problem. Its not:

> 
curl -O https://iso.reactos.org/bootcd/lastest && ren lastest lastest_bootcd.7z && 7z e lastest_bootcd.7z && del lastest_bootcd.7z
> 
It's
> 
curl -O https://iso.reactos.org/bootcd/latest && ren latest latest_bootcd.7z && 7z e latest_bootcd.7z && del latest_bootcd.7z
>
Please correct this. :)

**Comment by Bassa31** [comment]
Sorry for problem :)
