### ISSUE TITLE
Rapps?

### ISSUE THREAD

**Issue by AwlsomeAlex** [AwlsomeAlex/ReactOS-Downloader#21]
What is the Windows folder for? Like what is downloader.cab for as well? Sorry i'm confused. @Bassa31

**Comment by Bassa31** [comment]
I want to modify Rapps for a new ReactOS Release Center

**Comment by AwlsomeAlex** [comment]
What is Rapps? @Bassa31

**Comment by Bassa31** [comment]
ReactOS Application Manager

**Comment by AwlsomeAlex** [comment]
So you're gonna modify it to be able to Download Versions of ReactOS? @Bassa31

**Comment by Bassa31** [comment]
Yes

**Comment by Bassa31** [comment]
I m working on this

**Comment by AwlsomeAlex** [comment]
That's pretty cool. Will it automatically Extract as well? And how did you do it? @Bassa31

**Comment by Bassa31** [comment]
It's C. Software Can download file zip but Can't extract for now

**Comment by AwlsomeAlex** [comment]
Okay @Bassa31 Looks Great. I may question, how is your English?

**Comment by Bassa31** [comment]
I think it's well ;)

**Comment by AwlsomeAlex** [comment]
Okay.
