### ISSUE TITLE
Complete Release 4.0 for Windows

### ISSUE THREAD

**Issue by AwlsomeAlex** [AwlsomeAlex/ReactOS-Downloader#23]
Hey, could you finish the installation center or release the program so we can get this show on the road? Thanks! :+1: Because I didn't see too much progress in the Windows Branch and was wondering if you forked the repository, so if you did Ill just create a pull request. Thanks again!

**Comment by Bassa31** [comment]
Hey,
Sorry I was too busy 
Yeah! If you want I can complete 0.4 release (no gui )
And I can write gui!

**Comment by AwlsomeAlex** [comment]
Okay great! @Bassa31

**Comment by Bassa31** [comment]
I need again 1/2 days and I Will release it ;)

**Comment by AwlsomeAlex** [comment]
Okay. @Bassa31

**Comment by Bassa31** [comment]
Release 0.4.0 will be a script. Maybe 0.5 will be program with gui :)

**Comment by Bassa31** [comment]
It is done. Can you test it? Thanks

**Comment by AwlsomeAlex** [comment]
Great! One more thing, can you please create another file called "Apps" or something like that and include the applications needed for running the script? Because the goal is to make it as easy as possible for someone inexperienced to use this, without having to download WGet. Thanks, then I will release the 2nd RC. @Bassa31
