### ISSUE TITLE
SourceForge: WGet can't download Sourceforge .zip & .7z

### ISSUE THREAD

**Issue by AwlsomeAlex** [AwlsomeAlex/ReactOS-Downloader#24]
For some reason, WGet won't download .zips nor .7z but will download .isos, will find a fix soon.

**Comment by Bassa31** [comment]
http://download.reactos.org is ReactOS mirror from Sourceforge. I suggest to try with it

**Comment by AwlsomeAlex** [comment]
@Bassa31 Thank you@ In the future I will have this as an alternative mirror option.
