### ISSUE TITLE
Ability to Download Latest Stable Builds

### ISSUE THREAD

**Issue by AwlsomeAlex** [AwlsomeAlex/ReactOS-Downloader#9]
Will most likely require a complete rewrite. :/
The plan is to have 3 Options,
* Download Stable
* Download Trunk
* Extras
(Along with Quit.)

**Comment by Bassa31** [comment]
Extras can be:
- ROSBE (reactos build environment)
- ReactOS Source
- Other stuff..

**Comment by AwlsomeAlex** [comment]
Great idea @Bassa31 another one will be ReactOS Pre-Releases. But that will have to include an update script for Release 4.0
